//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.10 at 09:20:39 PM CET 
//


package com.live.order.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for FoodItemType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FoodItemType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Snacks"/>
 *     &lt;enumeration value="Beverages"/>
 *     &lt;enumeration value="Starters"/>
 *     &lt;enumeration value="Meals"/>
 *     &lt;enumeration value="Coffee"/>
 *     &lt;enumeration value="Juices"/>
 *     &lt;enumeration value="Desserts"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum FoodItemType {

    @XmlEnumValue("Beverages")
    BEVERAGES("Beverages"),
    @XmlEnumValue("Coffee")
    COFFEE("Coffee"),
    @XmlEnumValue("Desserts")
    DESSERTS("Desserts"),
    @XmlEnumValue("Juices")
    JUICES("Juices"),
    @XmlEnumValue("Meals")
    MEALS("Meals"),
    @XmlEnumValue("Snacks")
    SNACKS("Snacks"),
    @XmlEnumValue("Starters")
    STARTERS("Starters");
    private final String value;

    FoodItemType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FoodItemType fromValue(String v) {
        for (FoodItemType c: FoodItemType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
