//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.10 at 09:20:39 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.smartrevolutionaryit.fr/OrderService/schema")
package com.live.order.domain;
